---
- name: setup rabbitmq
  hosts: rabbitmq
  become: yes

  tasks: 
   - name: add rabbitmq repo
     ansible.builtin.copy:
       src: rabbitmq.repo
       dest: /etc/yum.repos.d/rabbitmq.repo

   - name: install rabbitmq-server
     ansible.builtin.package:
       name: rabbitmq-server
       state: present

   - name: start and enable rabbitmq-server
     ansible.builtin.service: 
       name: rabbitmq-server
       state: started
       enabled: yes

   - name: add rabbitmq user
     community.rabbitmq.rabbitmq_user:
       name: roboshop
       password: raboshop123
       state: present
       permissions:
         - vhost: /
           read_priv: .*
           write_priv: .*
           configure_priv: .*

   - name: check rabbitmq port
     ansible.builtin.command: netstat -lntp
     register: rabbitmqport

   - name: print port
     ansible.builtin.debug:
       msg: "{{ rabbitmqport }}"

   - name: check rabbitmq user
     ansible.builtin.command: cat /etc/passwd
     register: user

   - name: print port
     ansible.builtin.debug:
       msg: "{{ user }}"
          